// <auto-generated />
using System;
using DAL.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TravelWeb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251108134100_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            NotificationDesc = "Online Olacaq",
                            NotificationStatus = true,
                            NotificationTitle = "Iclas",
                            NotificationType = "warning",
                            NotificationTypeColor = "preview-icon bg-success",
                            NotificationTypeIcon = "mdi mdi-calendar"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SliderId"));

                    b.Property<string>("SliderBanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SliderStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SliderTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SliderTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SliderId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            SliderId = 1,
                            SliderBanner = "/web/assets/images/banner1.jpg",
                            SliderStatus = true,
                            SliderTitle1 = "Seyahetin Dadını Çıxart",
                            SliderTitle2 = "Dünyaya Ferqli Bax"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WriterImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WriterStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutID"));

                    b.Property<int>("AboutDetail")
                        .HasColumnType("int");

                    b.Property<int>("AboutImage1")
                        .HasColumnType("int");

                    b.Property<int>("AboutStatus")
                        .HasColumnType("int");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AboutTitle2")
                        .HasColumnType("int");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.About2", b =>
                {
                    b.Property<int>("About2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("About2ID"));

                    b.Property<int>("About2Description")
                        .HasColumnType("int");

                    b.Property<int>("About2Image")
                        .HasColumnType("int");

                    b.Property<string>("About2Title1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About2Title2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AboutStatus")
                        .HasColumnType("int");

                    b.HasKey("About2ID");

                    b.ToTable("Abouts2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<bool?>("CommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommentUserComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentUserMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("DestinationId");

                    b.HasIndex("WriterId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<int>("CapaCity")
                        .HasColumnType("int");

                    b.Property<int>("CommentID")
                        .HasColumnType("int");

                    b.Property<string>("DestinationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationCountLimit")
                        .HasColumnType("int");

                    b.Property<string>("DestinationDayNight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DestinationPrice")
                        .HasColumnType("float");

                    b.Property<bool>("DestinationStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DestinationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GuideID")
                        .HasColumnType("int");

                    b.Property<int>("TestimonialID")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId");

                    b.HasIndex("GuideID");

                    b.HasIndex("TestimonialID");

                    b.HasIndex("WriterId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CapaCity = 25,
                            CommentID = 0,
                            DestinationCity = "Bakı",
                            DestinationCountLimit = 30,
                            DestinationDayNight = "3 gün 2 gecə",
                            DestinationImage = "/web/assets/images/g1.jpg",
                            DestinationPrice = 350.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(10),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 1,
                            TestimonialID = 1,
                            UserId = 1
                        },
                        new
                        {
                            DestinationId = 2,
                            CapaCity = 20,
                            CommentID = 0,
                            DestinationCity = "Qəbələ",
                            DestinationCountLimit = 25,
                            DestinationDayNight = "2 gün 1 gecə",
                            DestinationImage = "/web/assets/images/g2.jpg",
                            DestinationPrice = 250.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(10),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 2,
                            TestimonialID = 2,
                            UserId = 2
                        },
                        new
                        {
                            DestinationId = 3,
                            CapaCity = 15,
                            CommentID = 0,
                            DestinationCity = "Şəki",
                            DestinationCountLimit = 20,
                            DestinationDayNight = "1 günlük tur",
                            DestinationImage = "/web/assets/images/g3.jpg",
                            DestinationPrice = 180.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(10),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 3,
                            TestimonialID = 3,
                            UserId = 3
                        },
                        new
                        {
                            DestinationId = 4,
                            CapaCity = 20,
                            CommentID = 0,
                            DestinationCity = "Quba",
                            DestinationCountLimit = 25,
                            DestinationDayNight = "3 gün 2 gecə",
                            DestinationImage = "/web/assets/images/g4.jpg",
                            DestinationPrice = 300.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(20),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 4,
                            TestimonialID = 4,
                            UserId = 1
                        },
                        new
                        {
                            DestinationId = 5,
                            CapaCity = 30,
                            CommentID = 0,
                            DestinationCity = "Şuşa",
                            DestinationCountLimit = 30,
                            DestinationDayNight = "4 gün 3 gecə",
                            DestinationImage = "/web/assets/images/g5.jpg",
                            DestinationPrice = 400.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(20),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 5,
                            TestimonialID = 5,
                            UserId = 2
                        },
                        new
                        {
                            DestinationId = 6,
                            CapaCity = 20,
                            CommentID = 0,
                            DestinationCity = "Lənkəran",
                            DestinationCountLimit = 25,
                            DestinationDayNight = "2 gün 1 gecə",
                            DestinationImage = "/web/assets/images/g6.jpg",
                            DestinationPrice = 270.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(20),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 6,
                            TestimonialID = 6,
                            UserId = 3
                        },
                        new
                        {
                            DestinationId = 7,
                            CapaCity = 25,
                            CommentID = 0,
                            DestinationCity = "Naftalan",
                            DestinationCountLimit = 30,
                            DestinationDayNight = "3 gün 2 gecə",
                            DestinationImage = "/web/assets/images/g7.jpg",
                            DestinationPrice = 320.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(30),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 7,
                            TestimonialID = 7,
                            UserId = 1
                        },
                        new
                        {
                            DestinationId = 8,
                            CapaCity = 15,
                            CommentID = 0,
                            DestinationCity = "İsmayıllı",
                            DestinationCountLimit = 20,
                            DestinationDayNight = "1 günlük tur",
                            DestinationImage = "/web/assets/images/g8.jpg",
                            DestinationPrice = 190.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(30),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 8,
                            TestimonialID = 8,
                            UserId = 2
                        },
                        new
                        {
                            DestinationId = 9,
                            CapaCity = 20,
                            CommentID = 0,
                            DestinationCity = "Qusar",
                            DestinationCountLimit = 25,
                            DestinationDayNight = "2 gün 1 gecə",
                            DestinationImage = "/web/assets/images/g9.jpg",
                            DestinationPrice = 260.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(40),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 9,
                            TestimonialID = 9,
                            UserId = 3
                        },
                        new
                        {
                            DestinationId = 10,
                            CapaCity = 25,
                            CommentID = 0,
                            DestinationCity = "Zaqatala",
                            DestinationCountLimit = 30,
                            DestinationDayNight = "3 gün 2 gecə",
                            DestinationImage = "/web/assets/images/g10.jpg",
                            DestinationPrice = 310.0,
                            DestinationStatus = true,
                            DestinationTime = new DateTime(2025, 11, 8, 17, 41, 0, 247, DateTimeKind.Local).AddTicks(40),
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 10,
                            TestimonialID = 10,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Feature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"));

                    b.Property<string>("FeatureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FeatureStatus")
                        .HasColumnType("bit");

                    b.HasKey("FeatureID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Feature2", b =>
                {
                    b.Property<int>("Feature2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feature2ID"));

                    b.Property<string>("Feature2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature2Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Feature2Status")
                        .HasColumnType("bit");

                    b.HasKey("Feature2ID");

                    b.ToTable("Features2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Guide", b =>
                {
                    b.Property<int>("GuideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuideID"));

                    b.Property<string>("GuideDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideFacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GuideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("GuideXUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuideID");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            GuideID = 1,
                            GuideDescription = "Azərbaycanın tarixi yerləri üzrə ixtisaslaşmış bələdçi.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Ceyhun Əliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 2,
                            GuideDescription = "Qəbələ və Şəki bölgələri üzrə təcrübəli bələdçi.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Nigar Məmmədova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 3,
                            GuideDescription = "Bakı şəhərinin mədəni və memarlıq abidələrini tanıdan peşəkar bələdçi.",
                            GuideImage = "/web/assets/images/team3.jpg",
                            GuideName = "Rauf Hüseynov",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 4,
                            GuideDescription = "Azərbaycan mətbəxi və ənənələri barədə tur bələdçisi.",
                            GuideImage = "/web/assets/images/team4.jpg",
                            GuideName = "Günel İsmayılova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 5,
                            GuideDescription = "Qarabağ və Şuşa istiqamətində tur rəhbəri.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Elvin Rzayev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 6,
                            GuideDescription = "Azərbaycanın təbiət parkları və yürüş turları üzrə mütəxəssis.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Aysel Qasımova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 7,
                            GuideDescription = "Qobustan və Abşeron yarımadası üzrə ixtisaslaşmış bələdçi.",
                            GuideImage = "/web/assets/images/team3.jpg",
                            GuideName = "Murad Əliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 8,
                            GuideDescription = "Mədəni və incəsənət turları üzrə təcrübəli bələdçi.",
                            GuideImage = "/web/assets/images/team4.jpg",
                            GuideName = "Zəhra Həsənli",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 9,
                            GuideDescription = "İçərişəhər və tarixi Bakı turları üzrə bələdçi.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Kamal Quliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 10,
                            GuideDescription = "Qusar, Quba və Xaçmaz bölgələri üzrə bələdçi.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Leyla Səlimova",
                            GuideStatus = true
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rezervation", b =>
                {
                    b.Property<int>("RezervationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervationID"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("RemainderCapaCity")
                        .HasColumnType("int");

                    b.Property<int>("RezervationCountPerson")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RezervationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RezervationDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("RezervationTime")
                        .HasColumnType("time");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.Property<int>("rezervationStatus")
                        .HasColumnType("int");

                    b.HasKey("RezervationID");

                    b.HasIndex("DestinationId");

                    b.HasIndex("WriterId");

                    b.ToTable("Rezervations");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rotasion", b =>
                {
                    b.Property<int>("RotasionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotasionID"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("RotasionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotasionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RotasionStatus")
                        .HasColumnType("bit");

                    b.HasKey("RotasionID");

                    b.HasIndex("DestinationId");

                    b.ToTable("Rotasions");

                    b.HasData(
                        new
                        {
                            RotasionID = 1,
                            DestinationId = 1,
                            RotasionDescription = "Tarixi abidələrə səyahət",
                            RotasionName = "Qobustan Qayaüstü",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 2,
                            DestinationId = 2,
                            RotasionDescription = "Təbiət gəzintisi və foto turları",
                            RotasionName = "Nohur Gölü",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 3,
                            DestinationId = 3,
                            RotasionDescription = "Mədəni ekskursiya",
                            RotasionName = "Xan Sarayı",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 4,
                            DestinationId = 4,
                            RotasionDescription = "Dağ yürüşü və piknik",
                            RotasionName = "Qəçrəş Meşəsi",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 5,
                            DestinationId = 5,
                            RotasionDescription = "Qarabağın ürəyi olan şəhər",
                            RotasionName = "Qalasına Ziyarət",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 6,
                            DestinationId = 5,
                            RotasionDescription = "Çay bağları və təbiət",
                            RotasionName = "Xalça Müzeyi",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 7,
                            DestinationId = 7,
                            RotasionDescription = "Spa və sağlamlıq turu",
                            RotasionName = "Naftalan Müalicə Mərkəzi",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 8,
                            DestinationId = 8,
                            RotasionDescription = "Ekoturizm və hiking",
                            RotasionName = "İsmayıllı Meşələri",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 9,
                            DestinationId = 9,
                            RotasionDescription = "Qar idmanı və xizək turu",
                            RotasionName = "Qış Mərkəzi",
                            RotasionStatus = true
                        },
                        new
                        {
                            RotasionID = 10,
                            DestinationId = 10,
                            RotasionDescription = "Təbiət və heyvanat dünyası ilə tanışlıq",
                            RotasionName = "Qoruğ",
                            RotasionStatus = true
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubAbout", b =>
                {
                    b.Property<int>("SubAboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubAboutID"));

                    b.Property<string>("SubAboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubAboutID");

                    b.ToTable("SubAbouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Testimonial", b =>
                {
                    b.Property<int>("TestimonialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialID"));

                    b.Property<string>("TestimonialClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TestimonialStatus")
                        .HasColumnType("bit");

                    b.HasKey("TestimonialID");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            TestimonialID = 1,
                            TestimonialClient = "Eldar Nəsibov",
                            TestimonialComment = "Tur zamanı hər şey əla idi!",
                            TestimonialImage = "/web/assets/images/test1.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 2,
                            TestimonialClient = "Ləman Abbasova",
                            TestimonialComment = "Bələdçilər çox mehriban idi.",
                            TestimonialImage = "/web/assets/images/test2.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 3,
                            TestimonialClient = "Kənan Quliyev",
                            TestimonialComment = "Maraqlı və rahat səyahət idi.",
                            TestimonialImage = "/web/assets/images/test3.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 4,
                            TestimonialClient = "Aytac Nəbiyeva",
                            TestimonialComment = "Qrup şəklində çox gözəl təşkil olunmuşdu.",
                            TestimonialImage = "/web/assets/images/test4.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 5,
                            TestimonialClient = "Rəşad Məmmədli",
                            TestimonialComment = "Foto məkanlar möhtəşəm idi.",
                            TestimonialImage = "/web/assets/images/test5.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 6,
                            TestimonialClient = "Sevda Həsənova",
                            TestimonialComment = "Ən sevdiyim tur agentliyidir!",
                            TestimonialImage = "/web/assets/images/test6.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 7,
                            TestimonialClient = "Orxan Əliyev",
                            TestimonialComment = "Qarabağ turu inanılmaz idi.",
                            TestimonialImage = "/web/assets/images/test7.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 8,
                            TestimonialClient = "Aysel Qasımova",
                            TestimonialComment = "Təbiət yürüşü çox zövqlü keçdi.",
                            TestimonialImage = "/web/assets/images/test8.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 9,
                            TestimonialClient = "Murad Hüseynov",
                            TestimonialComment = "Təşkilatçılıq yüksək səviyyədə idi.",
                            TestimonialImage = "/web/assets/images/test9.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 10,
                            TestimonialClient = "Nigar Məmmədli",
                            TestimonialComment = "Gələn dəfə də sizlərlə gedəcəm!",
                            TestimonialImage = "/web/assets/images/test10.jpg",
                            TestimonialStatus = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Destination", "Destination")
                        .WithMany("Comments")
                        .HasForeignKey("DestinationId");

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Destination");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Guide", null)
                        .WithMany("Destinations")
                        .HasForeignKey("GuideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Testimonial", "Testimonial")
                        .WithMany("Destinations")
                        .HasForeignKey("TestimonialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Testimonial");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rezervation", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Destination");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rotasion", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Destination", "Destination")
                        .WithMany("Rotasions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Rotasions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Guide", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Testimonial", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
