// <auto-generated />
using System;
using DAL.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TravelWeb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251111025458_migCleanStart")]
    partial class migCleanStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutID"));

                    b.Property<int>("AboutDetail")
                        .HasColumnType("int");

                    b.Property<int>("AboutImage1")
                        .HasColumnType("int");

                    b.Property<int>("AboutStatus")
                        .HasColumnType("int");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AboutTitle2")
                        .HasColumnType("int");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("Entities.Concrete.About2", b =>
                {
                    b.Property<int>("About2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("About2ID"));

                    b.Property<int>("About2Description")
                        .HasColumnType("int");

                    b.Property<int>("About2Image")
                        .HasColumnType("int");

                    b.Property<string>("About2Title1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About2Title2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AboutStatus")
                        .HasColumnType("int");

                    b.HasKey("About2ID");

                    b.ToTable("Abouts2");
                });

            modelBuilder.Entity("Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<bool?>("CommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommentUserComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentUserMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("TourId");

                    b.HasIndex("WriterId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Entities.Concrete.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("DestinationCity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            DestinationCity = "Bakı"
                        },
                        new
                        {
                            DestinationId = 2,
                            DestinationCity = "Qəbələ"
                        },
                        new
                        {
                            DestinationId = 3,
                            DestinationCity = "Şəki"
                        },
                        new
                        {
                            DestinationId = 4,
                            DestinationCity = "Quba"
                        },
                        new
                        {
                            DestinationId = 5,
                            DestinationCity = "Şuşa"
                        },
                        new
                        {
                            DestinationId = 6,
                            DestinationCity = "Lənkəran"
                        },
                        new
                        {
                            DestinationId = 7,
                            DestinationCity = "Naftalan"
                        },
                        new
                        {
                            DestinationId = 8,
                            DestinationCity = "İsmayıllı"
                        },
                        new
                        {
                            DestinationId = 9,
                            DestinationCity = "Qusar"
                        },
                        new
                        {
                            DestinationId = 10,
                            DestinationCity = "Zaqatala"
                        },
                        new
                        {
                            DestinationId = 11,
                            DestinationCity = "Qazax"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Feature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"));

                    b.Property<string>("FeatureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FeatureStatus")
                        .HasColumnType("bit");

                    b.HasKey("FeatureID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Entities.Concrete.Feature2", b =>
                {
                    b.Property<int>("Feature2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feature2ID"));

                    b.Property<string>("Feature2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature2Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Feature2Status")
                        .HasColumnType("bit");

                    b.HasKey("Feature2ID");

                    b.ToTable("Features2");
                });

            modelBuilder.Entity("Entities.Concrete.Guide", b =>
                {
                    b.Property<int>("GuideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuideID"));

                    b.Property<string>("GuideDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideFacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GuideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("GuideXUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuideID");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            GuideID = 1,
                            GuideDescription = "Azərbaycanın tarixi yerləri üzrə ixtisaslaşmış bələdçi.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Ceyhun Əliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 2,
                            GuideDescription = "Qəbələ və Şəki bölgələri üzrə təcrübəli bələdçi.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Nigar Məmmədova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 3,
                            GuideDescription = "Bakı şəhərinin mədəni və memarlıq abidələrini tanıdan peşəkar bələdçi.",
                            GuideImage = "/web/assets/images/team3.jpg",
                            GuideName = "Rauf Hüseynov",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 4,
                            GuideDescription = "Azərbaycan mətbəxi və ənənələri barədə tur bələdçisi.",
                            GuideImage = "/web/assets/images/team4.jpg",
                            GuideName = "Günel İsmayılova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 5,
                            GuideDescription = "Qarabağ və Şuşa istiqamətində tur rəhbəri.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Elvin Rzayev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 6,
                            GuideDescription = "Azərbaycanın təbiət parkları və yürüş turları üzrə mütəxəssis.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Aysel Qasımova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 7,
                            GuideDescription = "Qobustan və Abşeron yarımadası üzrə ixtisaslaşmış bələdçi.",
                            GuideImage = "/web/assets/images/team3.jpg",
                            GuideName = "Murad Əliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 8,
                            GuideDescription = "Mədəni və incəsənət turları üzrə təcrübəli bələdçi.",
                            GuideImage = "/web/assets/images/team4.jpg",
                            GuideName = "Zəhra Həsənli",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 9,
                            GuideDescription = "İçərişəhər və tarixi Bakı turları üzrə bələdçi.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Kamal Quliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 10,
                            GuideDescription = "Qusar, Quba və Xaçmaz bölgələri üzrə bələdçi.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Leyla Səlimova",
                            GuideStatus = true
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            NotificationDesc = "Online Olacaq",
                            NotificationStatus = true,
                            NotificationTitle = "Iclas",
                            NotificationType = "warning",
                            NotificationTypeColor = "preview-icon bg-success",
                            NotificationTypeIcon = "mdi mdi-calendar"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Rezervation", b =>
                {
                    b.Property<int>("RezervationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervationID"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("RemainderCapaCity")
                        .HasColumnType("int");

                    b.Property<int>("RezervationCountPerson")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RezervationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RezervationDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("RezervationTime")
                        .HasColumnType("time");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.Property<int>("rezervationStatus")
                        .HasColumnType("int");

                    b.HasKey("RezervationID");

                    b.HasIndex("TourId");

                    b.HasIndex("WriterId");

                    b.ToTable("Rezervations");
                });

            modelBuilder.Entity("Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Rotasion", b =>
                {
                    b.Property<int>("RotasionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotasionID"));

                    b.Property<string>("RotasionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotasionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RotasionStatus")
                        .HasColumnType("bit");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("RotasionID");

                    b.HasIndex("TourId");

                    b.ToTable("Rotasions");

                    b.HasData(
                        new
                        {
                            RotasionID = 1,
                            RotasionDescription = "Bakı İçərişəhərin simvolu, tarixi abidə.",
                            RotasionName = "Qız Qalası",
                            RotasionStatus = true,
                            TourId = 1
                        },
                        new
                        {
                            RotasionID = 2,
                            RotasionDescription = "Orta əsr memarlığının incisi.",
                            RotasionName = "Şirvanşahlar Sarayı",
                            RotasionStatus = true,
                            TourId = 1
                        },
                        new
                        {
                            RotasionID = 3,
                            RotasionDescription = "Xəzər sahili boyunca səyahət və foto çəkilişlər.",
                            RotasionName = "Bulvar Gəzintisi",
                            RotasionStatus = true,
                            TourId = 2
                        },
                        new
                        {
                            RotasionID = 4,
                            RotasionDescription = "Bakı gecəsinin parlayan simvolu.",
                            RotasionName = "Flame Towers Panorama",
                            RotasionStatus = true,
                            TourId = 2
                        },
                        new
                        {
                            RotasionID = 5,
                            RotasionDescription = "Xizək və teleferik macərası.",
                            RotasionName = "Tufandağ Kompleksi",
                            RotasionStatus = true,
                            TourId = 3
                        },
                        new
                        {
                            RotasionID = 6,
                            RotasionDescription = "Qəbələnd əyləncə parkında istirahət.",
                            RotasionName = "Qəbələ Əyləncə Mərkəzi",
                            RotasionStatus = true,
                            TourId = 3
                        },
                        new
                        {
                            RotasionID = 7,
                            RotasionDescription = "Təbiət qoynunda sakitlik və foto turları.",
                            RotasionName = "Nohur Gölü",
                            RotasionStatus = true,
                            TourId = 4
                        },
                        new
                        {
                            RotasionID = 8,
                            RotasionDescription = "Dağlıq ərazidə gəzinti və sərin hava.",
                            RotasionName = "Yeddi Gözəl Şəlaləsi",
                            RotasionStatus = true,
                            TourId = 4
                        },
                        new
                        {
                            RotasionID = 9,
                            RotasionDescription = "Şəki xanlarının tarixi iqamətgahı.",
                            RotasionName = "Xan Sarayı",
                            RotasionStatus = true,
                            TourId = 5
                        },
                        new
                        {
                            RotasionID = 10,
                            RotasionDescription = "İpək Yolu üzərində qədim karvansaray kompleksi.",
                            RotasionName = "Karvansaray",
                            RotasionStatus = true,
                            TourId = 5
                        },
                        new
                        {
                            RotasionID = 11,
                            RotasionDescription = "Qafqazın ən qədim kilsələrindən biri.",
                            RotasionName = "Kiş Kilsəsi",
                            RotasionStatus = true,
                            TourId = 5
                        },
                        new
                        {
                            RotasionID = 12,
                            RotasionDescription = "Meşəlikdə yürüş və piknik.",
                            RotasionName = "Qəçrəş Meşəsi",
                            RotasionStatus = true,
                            TourId = 6
                        },
                        new
                        {
                            RotasionID = 13,
                            RotasionDescription = "Təbiətin nadir gözəlliyi, dağlıq ərazi.",
                            RotasionName = "Afurd Şəlaləsi",
                            RotasionStatus = true,
                            TourId = 6
                        },
                        new
                        {
                            RotasionID = 14,
                            RotasionDescription = "Qafqazın ən qədim yaşayış məskəni.",
                            RotasionName = "Xınalıq Kəndi",
                            RotasionStatus = true,
                            TourId = 7
                        },
                        new
                        {
                            RotasionID = 15,
                            RotasionDescription = "Unikal yəhudi məhəlləsi və mədəniyyət.",
                            RotasionName = "Quba Qırmızı Qəsəbə",
                            RotasionStatus = true,
                            TourId = 7
                        },
                        new
                        {
                            RotasionID = 16,
                            RotasionDescription = "Qarabağın ürəyində tarixi qala.",
                            RotasionName = "Şuşa Qalası",
                            RotasionStatus = true,
                            TourId = 8
                        },
                        new
                        {
                            RotasionID = 17,
                            RotasionDescription = "Qarabağ mənzərələri və açıq hava tədbirləri.",
                            RotasionName = "Cıdır Düzü",
                            RotasionStatus = true,
                            TourId = 8
                        },
                        new
                        {
                            RotasionID = 18,
                            RotasionDescription = "İslam memarlığının incisi.",
                            RotasionName = "Gövhər Ağa Məscidi",
                            RotasionStatus = true,
                            TourId = 8
                        },
                        new
                        {
                            RotasionID = 19,
                            RotasionDescription = "Ekoturizm və dağ yürüşləri.",
                            RotasionName = "Hirkan Meşəsi",
                            RotasionStatus = true,
                            TourId = 9
                        },
                        new
                        {
                            RotasionID = 20,
                            RotasionDescription = "Dəniz kənarında gün batımı.",
                            RotasionName = "Mayak Sahili",
                            RotasionStatus = true,
                            TourId = 9
                        },
                        new
                        {
                            RotasionID = 21,
                            RotasionDescription = "Naftalan neft vannası və sağlamlıq mərkəzi.",
                            RotasionName = "Sanatoriya Kompleksi",
                            RotasionStatus = true,
                            TourId = 10
                        },
                        new
                        {
                            RotasionID = 22,
                            RotasionDescription = "Şəhər parkında istirahət və gəzinti.",
                            RotasionName = "Naftalan Parkı",
                            RotasionStatus = true,
                            TourId = 10
                        },
                        new
                        {
                            RotasionID = 23,
                            RotasionDescription = "Misgərlik və əl sənətkarlıq mərkəzi.",
                            RotasionName = "Lahıc Kəndi",
                            RotasionStatus = true,
                            TourId = 11
                        },
                        new
                        {
                            RotasionID = 24,
                            RotasionDescription = "Kənd həyatı və yerli mədəniyyət.",
                            RotasionName = "Basqal Kəndi",
                            RotasionStatus = true,
                            TourId = 11
                        },
                        new
                        {
                            RotasionID = 25,
                            RotasionDescription = "Dağ yürüşü və teleferik səyahəti.",
                            RotasionName = "Şahdağ Dağ Yolu",
                            RotasionStatus = true,
                            TourId = 12
                        },
                        new
                        {
                            RotasionID = 26,
                            RotasionDescription = "Dağlıq kənd həyatı və foto turlar.",
                            RotasionName = "Ləzə Kəndi",
                            RotasionStatus = true,
                            TourId = 12
                        },
                        new
                        {
                            RotasionID = 27,
                            RotasionDescription = "Tarixi qala və şəhər mənzərələri.",
                            RotasionName = "Zaqatala Qalası",
                            RotasionStatus = true,
                            TourId = 13
                        },
                        new
                        {
                            RotasionID = 28,
                            RotasionDescription = "Mədəni kənd turu və yerli mətbəx.",
                            RotasionName = "Yuxarı Çardaqlar",
                            RotasionStatus = true,
                            TourId = 13
                        },
                        new
                        {
                            RotasionID = 29,
                            RotasionDescription = "Zirvəyə yürüş və mənzərəli foto turları.",
                            RotasionName = "Göyəzən Dağı",
                            RotasionStatus = true,
                            TourId = 14
                        },
                        new
                        {
                            RotasionID = 30,
                            RotasionDescription = "Tarixi abidə və Qazax çayı ətrafı gəzinti.",
                            RotasionName = "Sınıq Körpü",
                            RotasionStatus = true,
                            TourId = 16
                        },
                        new
                        {
                            RotasionID = 31,
                            RotasionDescription = "Qazaxın qədim müdafiə istehkamı.",
                            RotasionName = "Qazax Qalası",
                            RotasionStatus = true,
                            TourId = 15
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SliderId"));

                    b.Property<string>("SliderBanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SliderStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SliderTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SliderTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SliderId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            SliderId = 1,
                            SliderBanner = "/web/assets/images/banner1.jpg",
                            SliderStatus = true,
                            SliderTitle1 = "Seyahetin Dadını Çıxart",
                            SliderTitle2 = "Dünyaya Ferqli Bax"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Testimonial", b =>
                {
                    b.Property<int>("TestimonialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialID"));

                    b.Property<string>("TestimonialClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TestimonialStatus")
                        .HasColumnType("bit");

                    b.HasKey("TestimonialID");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            TestimonialID = 1,
                            TestimonialClient = "Eldar Nəsibov",
                            TestimonialComment = "Tur zamanı hər şey əla idi!",
                            TestimonialImage = "/web/assets/images/test1.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 2,
                            TestimonialClient = "Ləman Abbasova",
                            TestimonialComment = "Bələdçilər çox mehriban idi.",
                            TestimonialImage = "/web/assets/images/test2.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 3,
                            TestimonialClient = "Kənan Quliyev",
                            TestimonialComment = "Maraqlı və rahat səyahət idi.",
                            TestimonialImage = "/web/assets/images/test3.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 4,
                            TestimonialClient = "Aytac Nəbiyeva",
                            TestimonialComment = "Qrup şəklində çox gözəl təşkil olunmuşdu.",
                            TestimonialImage = "/web/assets/images/test4.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 5,
                            TestimonialClient = "Rəşad Məmmədli",
                            TestimonialComment = "Foto məkanlar möhtəşəm idi.",
                            TestimonialImage = "/web/assets/images/test5.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 6,
                            TestimonialClient = "Sevda Həsənova",
                            TestimonialComment = "Ən sevdiyim tur agentliyidir!",
                            TestimonialImage = "/web/assets/images/test6.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 7,
                            TestimonialClient = "Orxan Əliyev",
                            TestimonialComment = "Qarabağ turu inanılmaz idi.",
                            TestimonialImage = "/web/assets/images/test7.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 8,
                            TestimonialClient = "Aysel Qasımova",
                            TestimonialComment = "Təbiət yürüşü çox zövqlü keçdi.",
                            TestimonialImage = "/web/assets/images/test8.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 9,
                            TestimonialClient = "Murad Hüseynov",
                            TestimonialComment = "Təşkilatçılıq yüksək səviyyədə idi.",
                            TestimonialImage = "/web/assets/images/test9.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 10,
                            TestimonialClient = "Nigar Məmmədli",
                            TestimonialComment = "Gələn dəfə də sizlərlə gedəcəm!",
                            TestimonialImage = "/web/assets/images/test10.jpg",
                            TestimonialStatus = true
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<int>("CommentID")
                        .HasColumnType("int");

                    b.Property<string>("DTourDayNight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("GuideID")
                        .HasColumnType("int");

                    b.Property<int>("TestimonialID")
                        .HasColumnType("int");

                    b.Property<int>("TourCapaCity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TourClock")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourCountLimit")
                        .HasColumnType("int");

                    b.Property<string>("TourDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourLocaion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TourPrice")
                        .HasColumnType("float");

                    b.Property<bool>("TourStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("TourId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("GuideID");

                    b.HasIndex("TestimonialID");

                    b.HasIndex("WriterId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            CommentID = 1,
                            DTourDayNight = "1 Gün",
                            DestinationId = 1,
                            GuideID = 1,
                            TestimonialID = 1,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 5,
                            TourDetail = "Bakı İçərişəhərin qədim küçələri və Qız qalası ziyarəti.",
                            TourImage = "/web/assets/images/g1.jpg",
                            TourLocaion = "İçərişəhər tarixi turu",
                            TourPrice = 40.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 2,
                            CommentID = 2,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 1,
                            GuideID = 2,
                            TestimonialID = 2,
                            TourCapaCity = 30,
                            TourClock = new DateTime(2025, 11, 11, 15, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 8,
                            TourDetail = "Panorama mənzərələri və Xəzər dənizi sahilində gəzinti.",
                            TourImage = "/web/assets/images/g2.jpg",
                            TourLocaion = "Flame Towers və Bulvar turu",
                            TourPrice = 85.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 3,
                            CommentID = 3,
                            DTourDayNight = "3 Gün 2 Gecə",
                            DestinationId = 2,
                            GuideID = 3,
                            TestimonialID = 3,
                            TourCapaCity = 20,
                            TourClock = new DateTime(2025, 11, 11, 10, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 5,
                            TourDetail = "Dağ-xizək istirahəti və Qəbələnin təbiəti.",
                            TourImage = "/web/assets/images/g3.jpg",
                            TourLocaion = "Tufandağ xizək turu",
                            TourPrice = 190.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 4,
                            CommentID = 4,
                            DTourDayNight = "1 Gün",
                            DestinationId = 2,
                            GuideID = 4,
                            TestimonialID = 4,
                            TourCapaCity = 35,
                            TourClock = new DateTime(2025, 11, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 10,
                            TourDetail = "Göl ətrafında rahat gəzinti və piknik.",
                            TourImage = "/web/assets/images/g4.jpg",
                            TourLocaion = "Nohur gölü gəzintisi",
                            TourPrice = 50.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 5,
                            CommentID = 5,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 3,
                            GuideID = 5,
                            TestimonialID = 5,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 7,
                            TourDetail = "Tarixi abidələr və Şəki mətbəxi.",
                            TourImage = "/web/assets/images/g5.jpg",
                            TourLocaion = "Şəki xan sarayı və karvansaray turu",
                            TourPrice = 110.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 6,
                            CommentID = 6,
                            DTourDayNight = "1 Gün",
                            DestinationId = 4,
                            GuideID = 6,
                            TestimonialID = 6,
                            TourCapaCity = 40,
                            TourClock = new DateTime(2025, 11, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 10,
                            TourDetail = "Meşəlikdə yürüş və istirahət.",
                            TourImage = "/web/assets/images/g6.jpg",
                            TourLocaion = "Qəçrəş meşə turu",
                            TourPrice = 60.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 7,
                            CommentID = 7,
                            DTourDayNight = "3 Gün 2 Gecə",
                            DestinationId = 4,
                            GuideID = 7,
                            TestimonialID = 7,
                            TourCapaCity = 20,
                            TourClock = new DateTime(2025, 11, 11, 12, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 5,
                            TourDetail = "Qafqazın ən qədim dağ kəndinə səyahət.",
                            TourImage = "/web/assets/images/g7.jpg",
                            TourLocaion = "Xınalıq kəndi turu",
                            TourPrice = 220.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 8,
                            CommentID = 8,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 5,
                            GuideID = 8,
                            TestimonialID = 8,
                            TourCapaCity = 20,
                            TourClock = new DateTime(2025, 11, 11, 10, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 6,
                            TourDetail = "Qarabağın simvolu olan şəhərdə tarixi gəzinti.",
                            TourImage = "/web/assets/images/g8.jpg",
                            TourLocaion = "Şuşa qalası və Cıdır düz turu",
                            TourPrice = 160.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 9,
                            CommentID = 9,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 6,
                            GuideID = 9,
                            TestimonialID = 9,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 8,
                            TourDetail = "Ekoturizm və meşə yürüşləri.",
                            TourImage = "/web/assets/images/g9.jpg",
                            TourLocaion = "Hirkan Milli Parkı turu",
                            TourPrice = 130.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 10,
                            CommentID = 10,
                            DTourDayNight = "3 Gün 2 Gecə",
                            DestinationId = 7,
                            GuideID = 10,
                            TestimonialID = 10,
                            TourCapaCity = 30,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 10,
                            TourDetail = "Müalicəvi neft vannaları və spa xidmətləri.",
                            TourImage = "/web/assets/images/g10.jpg",
                            TourLocaion = "Naftalan sanatoriya istirahəti",
                            TourPrice = 200.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 11,
                            CommentID = 11,
                            DTourDayNight = "1 Gün",
                            DestinationId = 8,
                            GuideID = 3,
                            TestimonialID = 1,
                            TourCapaCity = 30,
                            TourClock = new DateTime(2025, 11, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 10,
                            TourDetail = "Əl işləri və misgərlik sənəti ilə tanışlıq.",
                            TourImage = "/web/assets/images/g1.jpg",
                            TourLocaion = "Lahıc kəndi sənətkarlıq turu",
                            TourPrice = 55.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 12,
                            CommentID = 12,
                            DTourDayNight = "3 Gün 2 Gecə",
                            DestinationId = 9,
                            GuideID = 4,
                            TestimonialID = 2,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 11, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 5,
                            TourDetail = "Xizək, dağ yürüşü və qış istirahəti.",
                            TourImage = "/web/assets/images/g2.jpg",
                            TourLocaion = "Şahdağ xizək kompleksi turu",
                            TourPrice = 250.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 13,
                            CommentID = 13,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 10,
                            GuideID = 5,
                            TestimonialID = 3,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 10, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 6,
                            TourDetail = "Tarixi qala və təbiət birləşməsi.",
                            TourImage = "/web/assets/images/g3.jpg",
                            TourLocaion = "Zaqatala qalası və mədəni tur",
                            TourPrice = 140.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 14,
                            CommentID = 14,
                            DTourDayNight = "1 Gün",
                            DestinationId = 11,
                            GuideID = 6,
                            TestimonialID = 4,
                            TourCapaCity = 30,
                            TourClock = new DateTime(2025, 11, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 10,
                            TourDetail = "Göyəzən dağının zirvəsinə yürüş və piknik.",
                            TourImage = "/web/assets/images/g4.jpg",
                            TourLocaion = "Göyəzən dağı turu",
                            TourPrice = 60.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 15,
                            CommentID = 15,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 11,
                            GuideID = 7,
                            TestimonialID = 5,
                            TourCapaCity = 20,
                            TourClock = new DateTime(2025, 11, 11, 12, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 5,
                            TourDetail = "Qazaxın qədim məscid və qalaları ilə tanışlıq.",
                            TourImage = "/web/assets/images/g5.jpg",
                            TourLocaion = "Qazax tarixi abidələr turu",
                            TourPrice = 125.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 16,
                            CommentID = 16,
                            DTourDayNight = "1 Gün",
                            DestinationId = 11,
                            GuideID = 8,
                            TestimonialID = 6,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 8,
                            TourDetail = "Qazaxın simvolik Sınıq Körpüsünü ziyarət.",
                            TourImage = "/web/assets/images/g6.jpg",
                            TourLocaion = "Sınıq Körpü turu",
                            TourPrice = 45.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 17,
                            CommentID = 17,
                            DTourDayNight = "1 Gün",
                            DestinationId = 5,
                            GuideID = 9,
                            TestimonialID = 7,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 13, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 7,
                            TourDetail = "Şuşanın mədəni irsi və mənzərələri.",
                            TourImage = "/web/assets/images/g7.jpg",
                            TourLocaion = "Şuşa şəhər panoraması",
                            TourPrice = 70.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 18,
                            CommentID = 18,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 8,
                            GuideID = 10,
                            TestimonialID = 8,
                            TourCapaCity = 30,
                            TourClock = new DateTime(2025, 11, 11, 16, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 8,
                            TourDetail = "Təbiət gəzintiləri və kamp fəaliyyəti.",
                            TourImage = "/web/assets/images/g8.jpg",
                            TourLocaion = "İsmayıllı meşə yürüşü",
                            TourPrice = 120.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 19,
                            CommentID = 19,
                            DTourDayNight = "3 Gün 2 Gecə",
                            DestinationId = 9,
                            GuideID = 3,
                            TestimonialID = 9,
                            TourCapaCity = 20,
                            TourClock = new DateTime(2025, 11, 11, 17, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 5,
                            TourDetail = "Qusar dağları boyunca yürüş və düşərgə.",
                            TourImage = "/web/assets/images/g9.jpg",
                            TourLocaion = "Qusar dağ yürüşü",
                            TourPrice = 210.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 20,
                            CommentID = 20,
                            DTourDayNight = "2 Gün 1 Gecə",
                            DestinationId = 6,
                            GuideID = 2,
                            TestimonialID = 10,
                            TourCapaCity = 25,
                            TourClock = new DateTime(2025, 11, 11, 18, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 8,
                            TourDetail = "Lənkəran çayı və qədim qalaları ziyarət.",
                            TourImage = "/web/assets/images/g10.jpg",
                            TourLocaion = "Lənkəran çay və qala turu",
                            TourPrice = 135.0,
                            TourStatus = true
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WriterImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WriterStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubAbout", b =>
                {
                    b.Property<int>("SubAboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubAboutID"));

                    b.Property<string>("SubAboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubAboutID");

                    b.ToTable("SubAbouts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Comment", b =>
                {
                    b.HasOne("Entities.Concrete.Tour", "Tour")
                        .WithMany("Comments")
                        .HasForeignKey("TourId");

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Tour");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("Entities.Concrete.Rezervation", b =>
                {
                    b.HasOne("Entities.Concrete.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Tour");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("Entities.Concrete.Rotasion", b =>
                {
                    b.HasOne("Entities.Concrete.Tour", "Tour")
                        .WithMany("Rotasions")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Entities.Concrete.Tour", b =>
                {
                    b.HasOne("Entities.Concrete.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Guide", "Guide")
                        .WithMany("Tours")
                        .HasForeignKey("GuideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Testimonial", "Testimonial")
                        .WithMany("Tours")
                        .HasForeignKey("TestimonialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Destination");

                    b.Navigation("Guide");

                    b.Navigation("Testimonial");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.Destination", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Entities.Concrete.Guide", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Entities.Concrete.Testimonial", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Entities.Concrete.Tour", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Rotasions");
                });
#pragma warning restore 612, 618
        }
    }
}
