// <auto-generated />
using System;
using DAL.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TravelWeb.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("NotificationDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTypeIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            NotificationDesc = "Online Olacaq",
                            NotificationStatus = true,
                            NotificationTitle = "Iclas",
                            NotificationType = "warning",
                            NotificationTypeColor = "preview-icon bg-success",
                            NotificationTypeIcon = "mdi mdi-calendar"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SliderId"));

                    b.Property<string>("SliderBanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SliderStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SliderTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SliderTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SliderId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            SliderId = 1,
                            SliderBanner = "/web/assets/images/banner1.jpg",
                            SliderStatus = true,
                            SliderTitle1 = "Seyahetin Dadını Çıxart",
                            SliderTitle2 = "Dünyaya Ferqli Bax"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<int>("CommentID")
                        .HasColumnType("int");

                    b.Property<string>("DTourDayNight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GuideID")
                        .HasColumnType("int");

                    b.Property<int>("TestimonialID")
                        .HasColumnType("int");

                    b.Property<int>("TourCapaCity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TourClock")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourCountLimit")
                        .HasColumnType("int");

                    b.Property<string>("TourDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TourLocaion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TourPrice")
                        .HasColumnType("float");

                    b.Property<bool>("TourStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("TourId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("GuideID");

                    b.HasIndex("TestimonialID");

                    b.HasIndex("WriterId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            CommentID = 0,
                            DestinationId = 1,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 1,
                            TestimonialID = 1,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Tarixi şəhər turu",
                            TourImage = "/web/assets/images/g1.jpg",
                            TourLocaion = "İçərişəhər turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 2,
                            CommentID = 0,
                            DestinationId = 1,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 2,
                            TestimonialID = 2,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Bulvar gəzintisi",
                            TourImage = "/web/assets/images/g2.jpg",
                            TourLocaion = "Dənizkənarı Bulvar turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 3,
                            CommentID = 0,
                            DestinationId = 1,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 3,
                            TestimonialID = 3,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 20, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Panorama turları",
                            TourImage = "/web/assets/images/g3.jpg",
                            TourLocaion = "Flame Towers turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 4,
                            CommentID = 0,
                            DestinationId = 2,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 3,
                            TestimonialID = 4,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 10, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Dağ-xizək turu",
                            TourImage = "/web/assets/images/g4.jpg",
                            TourLocaion = "Tufandağ turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 5,
                            CommentID = 0,
                            DestinationId = 2,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 4,
                            TestimonialID = 5,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 15, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Göl ətrafında gəzinti",
                            TourImage = "/web/assets/images/g5.jpg",
                            TourLocaion = "Nohur gölü turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 6,
                            CommentID = 0,
                            DestinationId = 2,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 5,
                            TestimonialID = 6,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 19, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Tarixi tur",
                            TourImage = "/web/assets/images/g6.jpg",
                            TourLocaion = "Qəbələ Qədim şəhəri turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 7,
                            CommentID = 0,
                            DestinationId = 3,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 6,
                            TestimonialID = 7,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Mədəniyyət turu",
                            TourImage = "/web/assets/images/g7.jpg",
                            TourLocaion = "Şəki xan sarayı turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 8,
                            CommentID = 0,
                            DestinationId = 3,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 7,
                            TestimonialID = 8,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 13, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Tarixi kilsə turları",
                            TourImage = "/web/assets/images/g8.jpg",
                            TourLocaion = "Kiş kəndi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 9,
                            CommentID = 0,
                            DestinationId = 3,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 7,
                            TestimonialID = 9,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 18, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Şirniyyat turu",
                            TourImage = "/web/assets/images/g9.jpg",
                            TourLocaion = "Şəki bazarı turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 10,
                            CommentID = 0,
                            DestinationId = 4,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 5,
                            TestimonialID = 10,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Meşə turu",
                            TourImage = "/web/assets/images/g10.jpg",
                            TourLocaion = "Qəçrəş turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 11,
                            CommentID = 0,
                            DestinationId = 4,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 8,
                            TestimonialID = 1,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Dağ kəndi turu",
                            TourImage = "/web/assets/images/g1.jpg",
                            TourLocaion = "Xınalıq turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 12,
                            CommentID = 0,
                            DestinationId = 4,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 9,
                            TestimonialID = 2,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 19, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Çay ətrafında gəzinti",
                            TourImage = "/web/assets/images/g2.jpg",
                            TourLocaion = "Qudyalçay turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 13,
                            CommentID = 0,
                            DestinationId = 5,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 7,
                            TestimonialID = 3,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 10, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Tarixi mədəni tur",
                            TourImage = "/web/assets/images/g3.jpg",
                            TourLocaion = "Cıdır düz turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 14,
                            CommentID = 0,
                            DestinationId = 5,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 9,
                            TestimonialID = 4,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 15, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Mədəni abidələr turu",
                            TourImage = "/web/assets/images/g4.jpg",
                            TourLocaion = "Yuxarı Gövhər Ağa məscidi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 15,
                            CommentID = 0,
                            DestinationId = 5,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 10,
                            TestimonialID = 5,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 20, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Qala turu",
                            TourImage = "/web/assets/images/g5.jpg",
                            TourLocaion = "Şuşa qalası turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 16,
                            CommentID = 0,
                            DestinationId = 6,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 9,
                            TestimonialID = 6,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Ekoturizm",
                            TourImage = "/web/assets/images/g6.jpg",
                            TourLocaion = "Hirkan Milli Parkı turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 17,
                            CommentID = 0,
                            DestinationId = 6,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 10,
                            TestimonialID = 7,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Dəniz gəzintisi",
                            TourImage = "/web/assets/images/g7.jpg",
                            TourLocaion = "Mayak sahili turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 18,
                            CommentID = 0,
                            DestinationId = 6,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 6,
                            TestimonialID = 8,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 19, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Tarixi yerlər turu",
                            TourImage = "/web/assets/images/g8.jpg",
                            TourLocaion = "Lənkəran qalası turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 19,
                            CommentID = 0,
                            DestinationId = 7,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 10,
                            TestimonialID = 9,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Müalicəvi istirahət",
                            TourImage = "/web/assets/images/g9.jpg",
                            TourLocaion = "Naftalan sanatoriyası turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 20,
                            CommentID = 0,
                            DestinationId = 7,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 5,
                            TestimonialID = 10,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 13, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Şəhər gəzintisi",
                            TourImage = "/web/assets/images/g10.jpg",
                            TourLocaion = "Naftalan şəhər mərkəzi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 21,
                            CommentID = 0,
                            DestinationId = 7,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 5,
                            TestimonialID = 1,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 18, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Açıq hava fəaliyyəti",
                            TourImage = "/web/assets/images/g1.jpg",
                            TourLocaion = "Naftalan parkı turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 22,
                            CommentID = 0,
                            DestinationId = 8,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 3,
                            TestimonialID = 2,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 8, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Əl sənətkarlıq turu",
                            TourImage = "/web/assets/images/g2.jpg",
                            TourLocaion = "Lahıc kəndi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 23,
                            CommentID = 0,
                            DestinationId = 8,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 5,
                            TestimonialID = 3,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 14, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Təbiət gəzintisi",
                            TourImage = "/web/assets/images/g3.jpg",
                            TourLocaion = "İsmayıllı meşələri turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 24,
                            CommentID = 0,
                            DestinationId = 8,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 3,
                            TestimonialID = 4,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 19, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Mədəni tur",
                            TourImage = "/web/assets/images/g4.jpg",
                            TourLocaion = "Basqal kəndi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 25,
                            CommentID = 0,
                            DestinationId = 9,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 9,
                            TestimonialID = 5,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Xizək turu",
                            TourImage = "/web/assets/images/g5.jpg",
                            TourLocaion = "Şahdağ turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 26,
                            CommentID = 0,
                            DestinationId = 9,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 4,
                            TestimonialID = 6,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 15, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Ailəvi istirahət",
                            TourImage = "/web/assets/images/g6.jpg",
                            TourLocaion = "Qusar şəhər parkı turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 27,
                            CommentID = 0,
                            DestinationId = 9,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 9,
                            TestimonialID = 7,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 20, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Dağ yürüşü",
                            TourImage = "/web/assets/images/g7.jpg",
                            TourLocaion = "Ləzə kəndi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 28,
                            CommentID = 0,
                            DestinationId = 10,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 8,
                            TestimonialID = 8,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 9, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Tarixi tur",
                            TourImage = "/web/assets/images/g8.jpg",
                            TourLocaion = "Zaqatala qalası turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 29,
                            CommentID = 0,
                            DestinationId = 10,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 2,
                            TestimonialID = 9,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 13, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Mədəni kənd turu",
                            TourImage = "/web/assets/images/g9.jpg",
                            TourLocaion = "Yuxarı Çardaqlar turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        },
                        new
                        {
                            TourId = 30,
                            CommentID = 0,
                            DestinationId = 10,
                            Guid = new Guid("00000000-0000-0000-0000-000000000000"),
                            GuideID = 1,
                            TestimonialID = 10,
                            TourCapaCity = 0,
                            TourClock = new DateTime(2025, 11, 11, 19, 0, 0, 0, DateTimeKind.Local),
                            TourCountLimit = 0,
                            TourDetail = "Təbiət və mədəniyyət turu",
                            TourImage = "/web/assets/images/g10.jpg",
                            TourLocaion = "Qalal kəndi turu",
                            TourPrice = 0.0,
                            TourStatus = true
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Writer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WriterImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WriterStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutID"));

                    b.Property<int>("AboutDetail")
                        .HasColumnType("int");

                    b.Property<int>("AboutImage1")
                        .HasColumnType("int");

                    b.Property<int>("AboutStatus")
                        .HasColumnType("int");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AboutTitle2")
                        .HasColumnType("int");

                    b.HasKey("AboutID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.About2", b =>
                {
                    b.Property<int>("About2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("About2ID"));

                    b.Property<int>("About2Description")
                        .HasColumnType("int");

                    b.Property<int>("About2Image")
                        .HasColumnType("int");

                    b.Property<string>("About2Title1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About2Title2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AboutStatus")
                        .HasColumnType("int");

                    b.HasKey("About2ID");

                    b.ToTable("Abouts2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<bool?>("CommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommentUserComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentUserMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("TourId");

                    b.HasIndex("WriterId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("DestinationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            DestinationCity = "Bakı",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 3,
                            DestinationCity = "Şəki",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 4,
                            DestinationCity = "Quba",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 2,
                            DestinationCity = "Qəbələ",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 5,
                            DestinationCity = "Şuşa",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 6,
                            DestinationCity = "Lənkəran",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 7,
                            DestinationCity = "Naftalan",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 8,
                            DestinationCity = "İsmayıllı",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 9,
                            DestinationCity = "Qusar",
                            TourId = 0
                        },
                        new
                        {
                            DestinationId = 10,
                            DestinationCity = "Zaqatala",
                            TourId = 0
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Feature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"));

                    b.Property<string>("FeatureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FeatureStatus")
                        .HasColumnType("bit");

                    b.HasKey("FeatureID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Feature2", b =>
                {
                    b.Property<int>("Feature2ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feature2ID"));

                    b.Property<string>("Feature2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature2Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Feature2Status")
                        .HasColumnType("bit");

                    b.HasKey("Feature2ID");

                    b.ToTable("Features2");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Guide", b =>
                {
                    b.Property<int>("GuideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuideID"));

                    b.Property<string>("GuideDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideFacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GuideStatus")
                        .HasColumnType("bit");

                    b.Property<string>("GuideXUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuideID");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            GuideID = 1,
                            GuideDescription = "Azərbaycanın tarixi yerləri üzrə ixtisaslaşmış bələdçi.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Ceyhun Əliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 2,
                            GuideDescription = "Qəbələ və Şəki bölgələri üzrə təcrübəli bələdçi.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Nigar Məmmədova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 3,
                            GuideDescription = "Bakı şəhərinin mədəni və memarlıq abidələrini tanıdan peşəkar bələdçi.",
                            GuideImage = "/web/assets/images/team3.jpg",
                            GuideName = "Rauf Hüseynov",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 4,
                            GuideDescription = "Azərbaycan mətbəxi və ənənələri barədə tur bələdçisi.",
                            GuideImage = "/web/assets/images/team4.jpg",
                            GuideName = "Günel İsmayılova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 5,
                            GuideDescription = "Qarabağ və Şuşa istiqamətində tur rəhbəri.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Elvin Rzayev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 6,
                            GuideDescription = "Azərbaycanın təbiət parkları və yürüş turları üzrə mütəxəssis.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Aysel Qasımova",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 7,
                            GuideDescription = "Qobustan və Abşeron yarımadası üzrə ixtisaslaşmış bələdçi.",
                            GuideImage = "/web/assets/images/team3.jpg",
                            GuideName = "Murad Əliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 8,
                            GuideDescription = "Mədəni və incəsənət turları üzrə təcrübəli bələdçi.",
                            GuideImage = "/web/assets/images/team4.jpg",
                            GuideName = "Zəhra Həsənli",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 9,
                            GuideDescription = "İçərişəhər və tarixi Bakı turları üzrə bələdçi.",
                            GuideImage = "/web/assets/images/team1.jpg",
                            GuideName = "Kamal Quliyev",
                            GuideStatus = true
                        },
                        new
                        {
                            GuideID = 10,
                            GuideDescription = "Qusar, Quba və Xaçmaz bölgələri üzrə bələdçi.",
                            GuideImage = "/web/assets/images/team2.jpg",
                            GuideName = "Leyla Səlimova",
                            GuideStatus = true
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rezervation", b =>
                {
                    b.Property<int>("RezervationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervationID"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("RemainderCapaCity")
                        .HasColumnType("int");

                    b.Property<int>("RezervationCountPerson")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RezervationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RezervationDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("RezervationTime")
                        .HasColumnType("time");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WriterId")
                        .HasColumnType("int");

                    b.Property<int>("rezervationStatus")
                        .HasColumnType("int");

                    b.HasKey("RezervationID");

                    b.HasIndex("TourId");

                    b.HasIndex("WriterId");

                    b.ToTable("Rezervations");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rotasion", b =>
                {
                    b.Property<int>("RotasionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotasionID"));

                    b.Property<string>("RotasionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotasionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RotasionStatus")
                        .HasColumnType("bit");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("RotasionID");

                    b.HasIndex("TourId");

                    b.ToTable("Rotasions");

                    b.HasData(
                        new
                        {
                            RotasionID = 1,
                            RotasionDescription = "Tarixi abidələrə səyahət",
                            RotasionName = "Qobustan Qayaüstü",
                            RotasionStatus = true,
                            TourId = 1
                        },
                        new
                        {
                            RotasionID = 2,
                            RotasionDescription = "Təbiət gəzintisi və foto turları",
                            RotasionName = "Nohur Gölü",
                            RotasionStatus = true,
                            TourId = 5
                        },
                        new
                        {
                            RotasionID = 3,
                            RotasionDescription = "Mədəni ekskursiya",
                            RotasionName = "Xan Sarayı",
                            RotasionStatus = true,
                            TourId = 7
                        },
                        new
                        {
                            RotasionID = 4,
                            RotasionDescription = "Dağ yürüşü və piknik",
                            RotasionName = "Qəçrəş Meşəsi",
                            RotasionStatus = true,
                            TourId = 10
                        },
                        new
                        {
                            RotasionID = 5,
                            RotasionDescription = "Qarabağın ürəyi",
                            RotasionName = "Şuşa qalası",
                            RotasionStatus = true,
                            TourId = 15
                        },
                        new
                        {
                            RotasionID = 6,
                            RotasionDescription = "Spa və sağlamlıq turu",
                            RotasionName = "Naftalan Müalicə Mərkəzi",
                            RotasionStatus = true,
                            TourId = 19
                        },
                        new
                        {
                            RotasionID = 7,
                            RotasionDescription = "Ekoturizm və hiking",
                            RotasionName = "İsmayıllı Meşələri",
                            RotasionStatus = true,
                            TourId = 23
                        },
                        new
                        {
                            RotasionID = 8,
                            RotasionDescription = "Qar idmanı və xizək",
                            RotasionName = "Şahdağ Mərkəzi",
                            RotasionStatus = true,
                            TourId = 25
                        },
                        new
                        {
                            RotasionID = 9,
                            RotasionDescription = "Tarixi səfər",
                            RotasionName = "Zaqatala Qalası",
                            RotasionStatus = true,
                            TourId = 28
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubAbout", b =>
                {
                    b.Property<int>("SubAboutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubAboutID"));

                    b.Property<string>("SubAboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubAboutID");

                    b.ToTable("SubAbouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Testimonial", b =>
                {
                    b.Property<int>("TestimonialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialID"));

                    b.Property<string>("TestimonialClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestimonialImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TestimonialStatus")
                        .HasColumnType("bit");

                    b.HasKey("TestimonialID");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            TestimonialID = 1,
                            TestimonialClient = "Eldar Nəsibov",
                            TestimonialComment = "Tur zamanı hər şey əla idi!",
                            TestimonialImage = "/web/assets/images/test1.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 2,
                            TestimonialClient = "Ləman Abbasova",
                            TestimonialComment = "Bələdçilər çox mehriban idi.",
                            TestimonialImage = "/web/assets/images/test2.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 3,
                            TestimonialClient = "Kənan Quliyev",
                            TestimonialComment = "Maraqlı və rahat səyahət idi.",
                            TestimonialImage = "/web/assets/images/test3.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 4,
                            TestimonialClient = "Aytac Nəbiyeva",
                            TestimonialComment = "Qrup şəklində çox gözəl təşkil olunmuşdu.",
                            TestimonialImage = "/web/assets/images/test4.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 5,
                            TestimonialClient = "Rəşad Məmmədli",
                            TestimonialComment = "Foto məkanlar möhtəşəm idi.",
                            TestimonialImage = "/web/assets/images/test5.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 6,
                            TestimonialClient = "Sevda Həsənova",
                            TestimonialComment = "Ən sevdiyim tur agentliyidir!",
                            TestimonialImage = "/web/assets/images/test6.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 7,
                            TestimonialClient = "Orxan Əliyev",
                            TestimonialComment = "Qarabağ turu inanılmaz idi.",
                            TestimonialImage = "/web/assets/images/test7.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 8,
                            TestimonialClient = "Aysel Qasımova",
                            TestimonialComment = "Təbiət yürüşü çox zövqlü keçdi.",
                            TestimonialImage = "/web/assets/images/test8.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 9,
                            TestimonialClient = "Murad Hüseynov",
                            TestimonialComment = "Təşkilatçılıq yüksək səviyyədə idi.",
                            TestimonialImage = "/web/assets/images/test9.jpg",
                            TestimonialStatus = true
                        },
                        new
                        {
                            TestimonialID = 10,
                            TestimonialClient = "Nigar Məmmədli",
                            TestimonialComment = "Gələn dəfə də sizlərlə gedəcəm!",
                            TestimonialImage = "/web/assets/images/test10.jpg",
                            TestimonialStatus = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Tour", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Guide", null)
                        .WithMany("Tours")
                        .HasForeignKey("GuideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Testimonial", "Testimonial")
                        .WithMany("Tours")
                        .HasForeignKey("TestimonialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Destination");

                    b.Navigation("Testimonial");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.HasOne("Entities.Concrete.Tour", "Tour")
                        .WithMany("Comments")
                        .HasForeignKey("TourId");

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Tour");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rezervation", b =>
                {
                    b.HasOne("Entities.Concrete.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.HasOne("Entities.Concrete.Writer", "Writer")
                        .WithMany()
                        .HasForeignKey("WriterId");

                    b.Navigation("Tour");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Rotasion", b =>
                {
                    b.HasOne("Entities.Concrete.Tour", "Tour")
                        .WithMany("Rotasions")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Entities.Concrete.Writer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.Tour", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Rotasions");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Guide", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Testimonial", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
